name             'chef-openstack'
maintainer       'SoftLayer'
maintainer_email 'psroufe@softlayer.com'
license          'All rights reserved'
description      'Installs and configures an OpenStack Havana cluster'
supports         'ubuntu', '= 12.04'
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version          '0.4.0'
depends          'partial_search'
depends          'mysql'
depends          'ntp'
