# -*- mode: ruby -*-
# vi: set ft=ruby :
# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"



Vagrant::Config.run do |config|
  #config.vm.box_url = 'http://files.vagrantup.com/precise64.box'
  config.vm.box_url = 'http://nitron-vagrant.s3-website-us-east-1.amazonaws.com/vagrant_ubuntu_12.04.3_amd64_virtualbox.box'
  config.vm.box = "vagrant_ubuntu_12.04.3_amd64_virtualbox.box"

  config.vm.define 'openstack' do |openstack_config|
	openstack_config.vm.host_name = 'openstack'
	openstack_config.vm.customize ["modifyvm", :id, "--memory", 4096, "--cpus", "4", "--natdnshostresolver1", "on", "--natdnsproxy1", "on"]
	openstack_config.vm.forward_port 80, 7081
	openstack_config.vm.forward_port 6080, 6080
	openstack_config.vm.forward_port 6081, 6081
	file_to_disk = 'c:/tmp/openstack_large_disk.vdi'
	openstack_config.vm.customize ['createhd', '--filename', file_to_disk, '--size', 50 * 1024]
    openstack_config.vm.customize ['storageattach', :id, '--storagectl', 'IDE Controller', '--port', 1, '--device', 0, '--type', 'hdd', '--medium', file_to_disk]
	openstack_config.vm.network :hostonly, "192.168.50.4", :adapter => 2
	openstack_config.vm.provision :shell do |shell|
      shell.path = "prepare-openstack.sh"
    end
  end

  config.vm.define 'chef-server' do |chef_server|
    chef_server.vm.host_name = 'chef-server'
	chef_server.vm.customize ["modifyvm", :id, "--memory", 1024, "--cpus", "2", "--natdnshostresolver1", "on", "--natdnsproxy1", "on"]
	chef_server.vm.forward_port 80, 80
	chef_server.vm.forward_port 443, 443
	chef_server.vm.network :hostonly, "192.168.50.5", :adapter => 2
	chef_server.vm.provision :shell do |shell|
      shell.path = "install-chef-server.sh"
    end
  end
  
  
end