# Defaults for Chef environment
default['admin']['password'] = 'passwordsf'
default['admin']['email'] = 'admin@cloud.com'
default['admin']['debug'] = 'False'
default['admin']['banner'] = '# Generated by SoftLayer OpenStack Cookbooks.' \
                             ' Changes will be overwritten by chef-client.'

# Use eth1 and eth0 if provisioning CCIs or custom hardware.
# SoftLayer's hardware servers use bond1 and bond0.
# default['network']['public_interface'] = 'bond1'
# default['network']['private_interface'] = 'bond0'
default['network']['public_interface'] = 'eth1'
default['network']['private_interface'] = 'eth0'


# MySQL cookbook overrides
override['mysql']['bind_address'] = '0.0.0.0'
override['mysql']['remove_test_database'] = true
override['mysql']['remove_anonymous_users'] = true
override['mysql']['tunable']['innodb_thread_concurrency'] = '0'
override['mysql']['tunable']['innodb_commit_concurrency'] = '0'
override['mysql']['tunable']['innodb_read_io_threads'] = '64'
override['mysql']['tunable']['innodb_write_io_threads'] = '64'


# NTP cookbook overrides
override['ntp']['servers'] = ['time.softlayer.com',
                              'time.service.networklayer.com']


# Cluster setup
# '<variable name>' => '<chef recipe name>'
default['admin']['cloud_network']['recipes'] = {
  'controller' => 'controller',
  'network' => 'neutron-network',
  'rabbitmq' => 'rabbitmq-server',
  'keystone' => 'keystone',
  'glance' => 'glance',
  'cinder' => 'cinder',
  'mysqlglance' => 'mysql-glance',
  'mysqlcinder' => 'mysql-cinder',
  'mysqlkeystone' => 'mysql-keystone',
  'mysqlnova' => 'mysql-nova',
  'mysqlneutron' => 'mysql-neutron'
}
